FROM mcr.microsoft.com/devcontainers/java:21

# Instalar ferramentas adicionais se necessário (o Maven já vem incluído na imagem base de Java da Microsoft)
RUN apt-get update && apt-get install -y git curl